### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by ConceivedIsland** [CiarenceW/MR223_plugin#1]
Loading into the game with the MR223 it causes this error to appear. Still seems to work fine though.
[Player.log](https://github.com/CiarenceW/MR223_plugin/files/14215244/Player.log)

![Receiver 2 Screenshot 2024 02 08 - 22 09 35 72](https://github.com/CiarenceW/MR223_plugin/assets/91149761/4ee53e29-d4a9-4a73-8474-b702f85e056d)

For claritys sake the mods I have installed are the AllGunsCampaign (and it's dependencies) and ClarencesUnbelieveableModifications.

**Comment by CiarenceW** [comment]
yeah it does that, I've just fixed it, I'll release a new improved version of the MR223 soon-ish

**Comment by CiarenceW** [comment]
I uploaded the fixed version 2day (yesterday for me) on ThunderStore, in case you haven't seen
